create table "public"."event_types" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "event_type" text not null default 'board'::text
);


alter table "public"."event_types" enable row level security;

create table "public"."events" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "event_type" text not null,
    "message" text,
    "detail" text,
    "shift_id" bigint,
    "patient_id" bigint,
    "state" json,
    "previous_event" bigint not null
);


alter table "public"."events" enable row level security;

create table "public"."patient_types" (
    "created_at" timestamp with time zone not null default now(),
    "patient_type" text not null default 'walk in'::text
);


alter table "public"."patient_types" enable row level security;

create table "public"."patients" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "room" text not null default 'None'::text,
    "patient_type" text not null,
    "shift_id" bigint not null,
    "supervisor_id" bigint
);


alter table "public"."patients" enable row level security;

create table "public"."provider_roles" (
    "created_at" timestamp with time zone not null default now(),
    "role" text not null default 'physician'::text
);


alter table "public"."provider_roles" enable row level security;

create table "public"."providers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "lname" text,
    "fname" text,
    "role" text
);


alter table "public"."providers" enable row level security;

create table "public"."shift_details" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "start_time" time without time zone,
    "end_time" time without time zone,
    "bonus" smallint not null default '0'::smallint,
    "shift_type" text
);


alter table "public"."shift_details" enable row level security;

create table "public"."shift_types" (
    "created_at" timestamp with time zone not null default now(),
    "shift_type" text not null default 'physician'::text
);


alter table "public"."shift_types" enable row level security;

create table "public"."shifts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "info_id" bigint not null,
    "provider_id" bigint not null
);


alter table "public"."shifts" enable row level security;

create table "public"."state" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "current" json not null
);


alter table "public"."state" enable row level security;

CREATE UNIQUE INDEX event_types_pkey ON public.event_types USING btree (event_type);

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id);

CREATE UNIQUE INDEX patient_types_pkey ON public.patient_types USING btree (patient_type);

CREATE UNIQUE INDEX patients_pkey ON public.patients USING btree (id);

CREATE UNIQUE INDEX provider_roles_pkey ON public.provider_roles USING btree (role);

CREATE UNIQUE INDEX providers_pkey ON public.providers USING btree (id);

CREATE UNIQUE INDEX schedule_pkey ON public.shifts USING btree (id);

CREATE UNIQUE INDEX shift_types_pkey ON public.shift_types USING btree (shift_type);

CREATE UNIQUE INDEX shifts_pkey ON public.shift_details USING btree (id);

CREATE UNIQUE INDEX state_pkey ON public.state USING btree (id);

alter table "public"."event_types" add constraint "event_types_pkey" PRIMARY KEY using index "event_types_pkey";

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "public"."patient_types" add constraint "patient_types_pkey" PRIMARY KEY using index "patient_types_pkey";

alter table "public"."patients" add constraint "patients_pkey" PRIMARY KEY using index "patients_pkey";

alter table "public"."provider_roles" add constraint "provider_roles_pkey" PRIMARY KEY using index "provider_roles_pkey";

alter table "public"."providers" add constraint "providers_pkey" PRIMARY KEY using index "providers_pkey";

alter table "public"."shift_details" add constraint "shifts_pkey" PRIMARY KEY using index "shifts_pkey";

alter table "public"."shift_types" add constraint "shift_types_pkey" PRIMARY KEY using index "shift_types_pkey";

alter table "public"."shifts" add constraint "schedule_pkey" PRIMARY KEY using index "schedule_pkey";

alter table "public"."state" add constraint "state_pkey" PRIMARY KEY using index "state_pkey";

alter table "public"."events" add constraint "events_event_type_fkey" FOREIGN KEY (event_type) REFERENCES event_types(event_type) not valid;

alter table "public"."events" validate constraint "events_event_type_fkey";

alter table "public"."events" add constraint "events_patient_id_fkey" FOREIGN KEY (patient_id) REFERENCES patients(id) not valid;

alter table "public"."events" validate constraint "events_patient_id_fkey";

alter table "public"."events" add constraint "events_shift_id_fkey" FOREIGN KEY (shift_id) REFERENCES shifts(id) not valid;

alter table "public"."events" validate constraint "events_shift_id_fkey";

alter table "public"."patients" add constraint "patients_shift_id_fkey" FOREIGN KEY (shift_id) REFERENCES shifts(id) not valid;

alter table "public"."patients" validate constraint "patients_shift_id_fkey";

alter table "public"."patients" add constraint "patients_supervisor_id_fkey" FOREIGN KEY (supervisor_id) REFERENCES shifts(id) not valid;

alter table "public"."patients" validate constraint "patients_supervisor_id_fkey";

alter table "public"."patients" add constraint "patients_type_fkey" FOREIGN KEY (patient_type) REFERENCES patient_types(patient_type) not valid;

alter table "public"."patients" validate constraint "patients_type_fkey";

alter table "public"."shifts" add constraint "shifts_info_id_fkey" FOREIGN KEY (info_id) REFERENCES shift_details(id) not valid;

alter table "public"."shifts" validate constraint "shifts_info_id_fkey";

alter table "public"."shifts" add constraint "shifts_provider_id_fkey" FOREIGN KEY (provider_id) REFERENCES providers(id) not valid;

alter table "public"."shifts" validate constraint "shifts_provider_id_fkey";


